#Swagger URI --> https://petstore.swagger.io

#User Model
post_user = https://petstore.swagger.io/v2/user
get_user = https://petstore.swagger.io/v2/user/{username}
update_user = https://petstore.swagger.io/v2/user/{username}
delete_user = https://petstore.swagger.io/v2/user/{username}

#Swagger  https://book.anhtester.com/swagger
base.url = https://book.anhtester.com
token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNtbXFmNGh6ZjBvNTI3dWsxdXZnNmd2b3UiLCJqaXQiOiIwMTljZjcyMC1jMzBkLTcwMDAtOTdkOC00NjI3M2M1NzFiZWYiLCJleHAiOjE3NzQxOTEwNDUsImlhdCI6MTc3MzY3MjY0NX0._ujR9H79p4mtb1f43pkOESAYLoCYxinnwNK_G0l0jfQ

#Default book information
name_default = This is a default book
categories_default = ["Default Category 1","Default Category 2"]
price_default = 123456
status_default = AVAILABLE
description_default = Description for a default book
pictures_default = ["/$book-image/thu-book-test-1/think-and-grow-rich-5_kji3.jpg"]
promotions_default = ["cmmtd68cm0o747uk1slv1g0b2"]
slug_default = slug-default

